/*
  File autogenerated by gengetopt version 2.14
  generated with the following command:
  /tmp/gengetopt-2.14/inst/bin/gengetopt -i abi2xml.ggo 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->input_file_given = 0 ;
  args_info->output_file_given = 0 ;
  args_info->input_dir_given = 0 ;
  args_info->output_dir_given = 0 ;
  args_info->abi_file_suffix_given = 0 ;
  args_info->int_vector_as_attribute_given = 0 ;
  args_info->input_encoding_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->input_file_arg = NULL;
  args_info->input_file_orig = NULL;
  args_info->output_file_arg = NULL;
  args_info->output_file_orig = NULL;
  args_info->input_dir_arg = NULL;
  args_info->input_dir_orig = NULL;
  args_info->output_dir_arg = NULL;
  args_info->output_dir_orig = NULL;
  args_info->abi_file_suffix_arg = gengetopt_strdup ("abi");
  args_info->abi_file_suffix_orig = NULL;
  args_info->input_encoding_arg = gengetopt_strdup ("Apple Roman");
  args_info->input_encoding_orig = NULL;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n%s\n", "This program parses the binary file format coming from an\nABI PRISM TM 377 DNA Sequencer and writes the information out as \nan xml file");
  printf("\nUsage: abi2xml [OPTIONS]...\n\n");
  printf("%s\n","  -h, --help                    Print help and exit");
  printf("%s\n","  -V, --version                 Print version and exit");
  printf("%s\n","  -i, --input-file=STRING       input abi file");
  printf("%s\n","  -o, --output-file=STRING      output xml file");
  printf("%s\n","  -I, --input-dir=STRING        input dir with abi files");
  printf("%s\n","  -O, --output-dir=STRING       output dir");
  printf("%s\n","  -s, --abi-file-suffix=STRING  suffix of abi files ( used with --input-dir )  \n                                  (default=`abi')");
  printf("%s\n","  -a, --int-vector-as-attribute write integer vectors inside attributes ( It \n                                  makes file size smaller )");
  printf("%s\n","  -e, --input-encoding=STRING   input string encoding.  Available encodings \n                                  listed at: \n                                  http://doc.trolltech.com/3.0/qtextcodec.html  \n                                  (default=`Apple Roman')");
  
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  
  if (args_info->input_file_arg)
    {
      free (args_info->input_file_arg); /* free previous argument */
      args_info->input_file_arg = 0;
    }
  if (args_info->input_file_orig)
    {
      free (args_info->input_file_orig); /* free previous argument */
      args_info->input_file_orig = 0;
    }
  if (args_info->output_file_arg)
    {
      free (args_info->output_file_arg); /* free previous argument */
      args_info->output_file_arg = 0;
    }
  if (args_info->output_file_orig)
    {
      free (args_info->output_file_orig); /* free previous argument */
      args_info->output_file_orig = 0;
    }
  if (args_info->input_dir_arg)
    {
      free (args_info->input_dir_arg); /* free previous argument */
      args_info->input_dir_arg = 0;
    }
  if (args_info->input_dir_orig)
    {
      free (args_info->input_dir_orig); /* free previous argument */
      args_info->input_dir_orig = 0;
    }
  if (args_info->output_dir_arg)
    {
      free (args_info->output_dir_arg); /* free previous argument */
      args_info->output_dir_arg = 0;
    }
  if (args_info->output_dir_orig)
    {
      free (args_info->output_dir_orig); /* free previous argument */
      args_info->output_dir_orig = 0;
    }
  if (args_info->abi_file_suffix_arg)
    {
      free (args_info->abi_file_suffix_arg); /* free previous argument */
      args_info->abi_file_suffix_arg = 0;
    }
  if (args_info->abi_file_suffix_orig)
    {
      free (args_info->abi_file_suffix_orig); /* free previous argument */
      args_info->abi_file_suffix_orig = 0;
    }
  if (args_info->input_encoding_arg)
    {
      free (args_info->input_encoding_arg); /* free previous argument */
      args_info->input_encoding_arg = 0;
    }
  if (args_info->input_encoding_orig)
    {
      free (args_info->input_encoding_orig); /* free previous argument */
      args_info->input_encoding_orig = 0;
    }
  
  clear_given (args_info);
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  if (args_info->help_given) {
    fprintf(outfile, "%s\n", "help");
  }
  if (args_info->version_given) {
    fprintf(outfile, "%s\n", "version");
  }
  if (args_info->input_file_given) {
    if (args_info->input_file_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "input-file", args_info->input_file_orig);
    } else {
      fprintf(outfile, "%s\n", "input-file");
    }
  }
  if (args_info->output_file_given) {
    if (args_info->output_file_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "output-file", args_info->output_file_orig);
    } else {
      fprintf(outfile, "%s\n", "output-file");
    }
  }
  if (args_info->input_dir_given) {
    if (args_info->input_dir_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "input-dir", args_info->input_dir_orig);
    } else {
      fprintf(outfile, "%s\n", "input-dir");
    }
  }
  if (args_info->output_dir_given) {
    if (args_info->output_dir_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "output-dir", args_info->output_dir_orig);
    } else {
      fprintf(outfile, "%s\n", "output-dir");
    }
  }
  if (args_info->abi_file_suffix_given) {
    if (args_info->abi_file_suffix_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "abi-file-suffix", args_info->abi_file_suffix_orig);
    } else {
      fprintf(outfile, "%s\n", "abi-file-suffix");
    }
  }
  if (args_info->int_vector_as_attribute_given) {
    fprintf(outfile, "%s\n", "int-vector-as-attribute");
  }
  if (args_info->input_encoding_given) {
    if (args_info->input_encoding_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "input-encoding", args_info->input_encoding_orig);
    } else {
      fprintf(outfile, "%s\n", "input-encoding");
    }
  }
  
  fclose (outfile);

  i = EXIT_SUCCESS;
  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}


/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  return EXIT_SUCCESS;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "input-file",	1, NULL, 'i' },
        { "output-file",	1, NULL, 'o' },
        { "input-dir",	1, NULL, 'I' },
        { "output-dir",	1, NULL, 'O' },
        { "abi-file-suffix",	1, NULL, 's' },
        { "int-vector-as-attribute",	0, NULL, 'a' },
        { "input-encoding",	1, NULL, 'e' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVi:o:I:O:s:ae:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'i':	/* input abi file.  */
          if (local_args_info.input_file_given)
            {
              fprintf (stderr, "%s: `--input-file' (`-i') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->input_file_given && ! override)
            continue;
          local_args_info.input_file_given = 1;
          args_info->input_file_given = 1;
          if (args_info->input_file_arg)
            free (args_info->input_file_arg); /* free previous string */
          args_info->input_file_arg = gengetopt_strdup (optarg);
          if (args_info->input_file_orig)
            free (args_info->input_file_orig); /* free previous string */
          args_info->input_file_orig = gengetopt_strdup (optarg);
          break;

        case 'o':	/* output xml file.  */
          if (local_args_info.output_file_given)
            {
              fprintf (stderr, "%s: `--output-file' (`-o') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->output_file_given && ! override)
            continue;
          local_args_info.output_file_given = 1;
          args_info->output_file_given = 1;
          if (args_info->output_file_arg)
            free (args_info->output_file_arg); /* free previous string */
          args_info->output_file_arg = gengetopt_strdup (optarg);
          if (args_info->output_file_orig)
            free (args_info->output_file_orig); /* free previous string */
          args_info->output_file_orig = gengetopt_strdup (optarg);
          break;

        case 'I':	/* input dir with abi files.  */
          if (local_args_info.input_dir_given)
            {
              fprintf (stderr, "%s: `--input-dir' (`-I') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->input_dir_given && ! override)
            continue;
          local_args_info.input_dir_given = 1;
          args_info->input_dir_given = 1;
          if (args_info->input_dir_arg)
            free (args_info->input_dir_arg); /* free previous string */
          args_info->input_dir_arg = gengetopt_strdup (optarg);
          if (args_info->input_dir_orig)
            free (args_info->input_dir_orig); /* free previous string */
          args_info->input_dir_orig = gengetopt_strdup (optarg);
          break;

        case 'O':	/* output dir.  */
          if (local_args_info.output_dir_given)
            {
              fprintf (stderr, "%s: `--output-dir' (`-O') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->output_dir_given && ! override)
            continue;
          local_args_info.output_dir_given = 1;
          args_info->output_dir_given = 1;
          if (args_info->output_dir_arg)
            free (args_info->output_dir_arg); /* free previous string */
          args_info->output_dir_arg = gengetopt_strdup (optarg);
          if (args_info->output_dir_orig)
            free (args_info->output_dir_orig); /* free previous string */
          args_info->output_dir_orig = gengetopt_strdup (optarg);
          break;

        case 's':	/* suffix of abi files ( used with --input-dir ).  */
          if (local_args_info.abi_file_suffix_given)
            {
              fprintf (stderr, "%s: `--abi-file-suffix' (`-s') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->abi_file_suffix_given && ! override)
            continue;
          local_args_info.abi_file_suffix_given = 1;
          args_info->abi_file_suffix_given = 1;
          if (args_info->abi_file_suffix_arg)
            free (args_info->abi_file_suffix_arg); /* free previous string */
          args_info->abi_file_suffix_arg = gengetopt_strdup (optarg);
          if (args_info->abi_file_suffix_orig)
            free (args_info->abi_file_suffix_orig); /* free previous string */
          args_info->abi_file_suffix_orig = gengetopt_strdup (optarg);
          break;

        case 'a':	/* write integer vectors inside attributes ( It makes file size smaller ).  */
          if (local_args_info.int_vector_as_attribute_given)
            {
              fprintf (stderr, "%s: `--int-vector-as-attribute' (`-a') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->int_vector_as_attribute_given && ! override)
            continue;
          local_args_info.int_vector_as_attribute_given = 1;
          args_info->int_vector_as_attribute_given = 1;
          break;

        case 'e':	/* input string encoding.  Available encodings listed at: http://doc.trolltech.com/3.0/qtextcodec.html.  */
          if (local_args_info.input_encoding_given)
            {
              fprintf (stderr, "%s: `--input-encoding' (`-e') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->input_encoding_given && ! override)
            continue;
          local_args_info.input_encoding_given = 1;
          args_info->input_encoding_given = 1;
          if (args_info->input_encoding_arg)
            free (args_info->input_encoding_arg); /* free previous string */
          args_info->input_encoding_arg = gengetopt_strdup (optarg);
          if (args_info->input_encoding_orig)
            free (args_info->input_encoding_orig); /* free previous string */
          args_info->input_encoding_orig = gengetopt_strdup (optarg);
          break;


        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
