/* cmdline.h */

/* File autogenerated by gengetopt version 2.14  */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "abi2xml"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "1.2"
#endif

struct gengetopt_args_info
{
  char * input_file_arg;	/* input abi file.  */
  char * input_file_orig;	/* input abi file original value given at command line.  */
  char * output_file_arg;	/* output xml file.  */
  char * output_file_orig;	/* output xml file original value given at command line.  */
  char * input_dir_arg;	/* input dir with abi files.  */
  char * input_dir_orig;	/* input dir with abi files original value given at command line.  */
  char * output_dir_arg;	/* output dir.  */
  char * output_dir_orig;	/* output dir original value given at command line.  */
  char * abi_file_suffix_arg;	/* suffix of abi files ( used with --input-dir ) (default='abi').  */
  char * abi_file_suffix_orig;	/* suffix of abi files ( used with --input-dir ) original value given at command line.  */
  char * input_encoding_arg;	/* input string encoding.  Available encodings listed at: http://doc.trolltech.com/3.0/qtextcodec.html (default='Apple Roman').  */
  char * input_encoding_orig;	/* input string encoding.  Available encodings listed at: http://doc.trolltech.com/3.0/qtextcodec.html original value given at command line.  */
  
  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int input_file_given ;	/* Whether input-file was given.  */
  int output_file_given ;	/* Whether output-file was given.  */
  int input_dir_given ;	/* Whether input-dir was given.  */
  int output_dir_given ;	/* Whether output-dir was given.  */
  int abi_file_suffix_given ;	/* Whether abi-file-suffix was given.  */
  int int_vector_as_attribute_given ;	/* Whether int-vector-as-attribute was given.  */
  int input_encoding_given ;	/* Whether input-encoding was given.  */

} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);
int cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required);
int cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

void cmdline_parser_init (struct gengetopt_args_info *args_info);
void cmdline_parser_free (struct gengetopt_args_info *args_info);

int cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
